"""rship user recipes

Revision ID: dd169c58fe79
Revises: bc866ea3d78f
Create Date: 2022-06-28 19:41:14.291441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd169c58fe79'
down_revision = 'bc866ea3d78f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
