"""drop ing table

Revision ID: f74fffd85abd
Revises: 2c3c3cb28ec9
Create Date: 2022-06-28 17:07:02.601034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74fffd85abd'
down_revision = '2c3c3cb28ec9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingredients_id', table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), nullable=True),
    sa.Column('creator', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingredients_id', 'ingredients', ['id'], unique=False)
    # ### end Alembic commands ###
